
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqlxmbwkucukhmioxall.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbHhtYndrdWN1a2htaW94YWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mjk3NTUsImV4cCI6MjA2NjAwNTc1NX0.SIznvyEjP_0bjfuEvoYJIIgBxSUkUyk7RRXsSnIc9YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
