// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkmevlxtuokslgpoxovi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbWV2bHh0dW9rc2xncG94b3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzY1NTMsImV4cCI6MjA2MjIxMjU1M30.xBA3daCknSiRfu6CouLZzWGjEuc3tVY3BE8V711PQtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);